database:
  url: '127.0.0.1'
  port: 3307
  name: 'test'
  username: 'root'
  password: 'a12345'
  type: 'mysql'
  tablePrefix: ""
  maxOpenConns: 1000
  maxIdleConns: 1000
  maxLifeTime: 5
  logMode: false
  version: "0.0.2"
